### ISSUE TITLE
Fix intermittently failing tests

### ISSUE THREAD

**Issue by cjcolvar** [ubiquitypress/hyku_addons#26]
- [x] rspec ./spec/models/concerns/hyku_addons/account_behavior_spec.rb:56
- [x] rspec ./spec/models/concerns/hyku_addons/account_behavior_spec.rb:86 (is this the same as above)?
- [x] rspec ./spec/features/create_generic_work_spec.rb:74
- [x] rspec ./spec/features/create_generic_work_spec.rb:151
- [x] rspec ./spec/services/hyku_addons/i18n_multitenant_spec.rb:13 # HykuAddons::I18nMultitenant.set changes the locale
- [x] rspec ./spec/features/bulkrax_import_spec.rb:37 # Bulkrax import import works imports works
- [x] rspec ./spec/jobs/register_doi_job_spec.rb:37

**Comment by thenapking** [comment]
Marking register_doi_job_spec as fixed in this PR https://github.com/ubiquitypress/hyku_addons/pull/536.  Please untick it if it starts failing again!

**Comment by thenapking** [comment]
Tests have not been failing intermittently now for over a month.  Test failures are now representing real failures rather than flaky tests.
