### ISSUE TITLE
Works always created 'private'

### ISSUE THREAD

**Issue by prdanelli** [ubiquitypress/hyku_addons#32]
When a work is created, no matter the visibility set, it seems to alway be set to private. When editing the work and changing the visibility, it seems to revert back to private. 

![admin](https://user-images.githubusercontent.com/1199977/103345104-61197c80-4a88-11eb-83c1-7df582de6f46.png)
![frontend](https://user-images.githubusercontent.com/1199977/103345105-61b21300-4a88-11eb-8037-9f0a0d0ff16a.png)

**Comment by cjcolvar** [comment]
Good catch.  I was able to reproduce this on AH demo.  This is an important one to fix.

**Comment by cjcolvar** [comment]
Fixed by #53
